spring:
  application:
    name: coding-challenge
  security:
    user:
      name: super
      password: super
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demoDB;MODE=MySql;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sapass
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect
    properties:
      format_sql: true
      use_sql_comments: true
    show-sql: true
fixer:
  baseCurrency: EUR
  api:
    url: http://data.fixer.io/api
    key: cd9017deef13c58b780f90c790002c0d